### ISSUE TITLE
any Chance to be updated to 1.19.4/1.20.x?

### ISSUE THREAD

**Issue by Cyclopropinon** [JanCantCode/auto-totem-detector#1]

**Comment by JanCantCode** [comment]
i might atleast attempt to update it to 1.20

**Comment by mroep** [comment]
> i might atleast attempt to update it to 1.20
Pls add it to 1.19.4 i mainly play cpvp there.

**Comment by SummerNugget** [comment]
I updated the repo to 1.19.4 already, you can now build the mod for 1.19.4 by downloading this repo, running `gradlew build` (or if you're on PowerShell or on Linux, run `./gradlew build`), waiting for it to finish, and after it does finish go into the newly created `build/libs` folder and moving the `anti-auto-totem-1.0.0-SNAPSHOT.jar` file into your mods folder. I might also make it work for *all* versions of 1.19 because this mod is quite simple and this task is pretty much easily possible. I'll consider doing that later though.

**Comment by SummerNugget** [comment]
Actually here's a MediaFire link to the JAR download, I'll ask JanDev later if he can upload the 1.19.4 JAR to modrinth. Here is the link for it (note: you have to have version 0.14.21 of the fabric loader, you can install if you don't have it by going to [the fabricmc website](fabricmc.net) and following the steps to install it): https://www.mediafire.com/file/bk19trm6n2nrhp6/anti-auto-totem-1.0-SNAPSHOT.jar/file
